import AuthProvider from './(components)/AuthProvider';
import Nav from './(components)/Nav';
import Footer from './(components)/Footer';
import './globals.css';


export const metadata = {
  title: 'Zuva Online KYC',
  description: 'Generated by IT Department:',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AuthProvider>
      <body className='bg-green-100'>
             
        <div className='min-h-screen'>
        <Nav/>  
        {children}
        {/* <Footer/> */}
        </div>        
      </body>
        </AuthProvider>
    </html>
  )
}
