import AuthProvider from './(components)/AuthProvider';
import Nav from './(components)/Nav';
import './globals.css';


export const metadata = {
  title: 'Zuva Online KYC',
  description: 'Generated by IT Department:',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AuthProvider>
      <body className='bg-gray-100'>
        <Nav/>        
        <div className='m-2 min-h-screen'>
        {children}
        </div>        
        </body>
        </AuthProvider>
    </html>
  )
}
